
modLoader="javafml"

loaderVersion="[4,)"

license="All rights reserved"

[registries]
structures = "legendarytiers:runic_house"

[[mods]]
modId = "legendarytiers"
version = "1.0.0"
displayName = "Legendary Tiers"


description='''
Tiers mod for RPG gameplay
'''

[[mixins]]
config="legendarytiers.mixins.json"


[[dependencies.legendarytiers]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.legendarytiers]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
