
modLoader="javafml"

loaderVersion="[4,)"

license="All rights reserved"

[registries]
structures = "legendarytiers:runic_house"

[[mods]]
modId = "legendarytiers"
version = "2.0.0"
displayName = "RPG Items Tiers (RIT)"


description='''
Tiers mod for RPG gaming.
Add new structure, attributes.
Add tiers, quiality and bonuses to tools, weapons, armor.
'''

[[mixins]]
config="legendarytiers.mixins.json"


[[dependencies.legendarytiers]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.legendarytiers]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
